<?php

$dbProducts = [
  //Cane
  new Food("Monghe All Breeds Adult Salmone e Riso", "cane", "Le crocchette di Monghe Salmone e Riso All Breeds Adult sono un alimento completo per cani adulti di tutte le taglie formulato con un'unica fonte proteica: il salmone.", "49,99", "https://arcaplanet.vtexassets.com/arquivos/ids/270797-200-200/Monge-All-Breeds-Adult-Salmone-e-Riso-12Kg.jpg?v=1781701785"),
  new Food("Virtue Dog Protein Selection Patè", "cane", "I patè Protein Selection di Virtue sono dei pregiati patè per cani, preparati con proteine selezionate di primissima qualità senza l'utilizzo di cereali, conservanti e coloranti.", "2,49", "https://arcaplanet.vtexassets.com/arquivos/ids/266207-200-200/virtus-dog-protein-selection-anatra-400g.jpg?v=1781702688"),
  new Food("Delizia Xs Ossi Masticabili", "cane", "Delizia XS con maiale sono ossi masticabili preparati con carne di pollo avvolta in pelle di maiale per soddisfare il palato dei cani con un peso tra i 2 e i 12 kg.", "5,49", "https://arcaplanet.vtexassets.com/arquivos/ids/223363-200-200/8in1-delights-cane-ossa-xs-maiale.jpg?v=1781568933"),
  new Food("Pedegrii Biscrook Biscotti Secchi", "cane", "I Biscrook sono biscotti per cani croccanti in 3 deliziose varietà, cotti alla perfezione. Renderai felice il tuo cane ogni giorno. ", "2,50", "https://arcaplanet.vtexassets.com/arquivos/ids/257498-200-200/35368-Biscrok-500g.jpg?v=1781701784"),
  //Gatto
  new Food("Crocchette", "gatto", "Crocchette ipocaloriche per gatti!", "14,99", "https://arcaplanet.vtexassets.com/arquivos/ids/271838-200-200/400.jpg?v=1781697451"),
  new Food("Umido", "gatto", "Umido 95% carne (provenienza Italia), 3% fibre e 1% vitamine!", "0,79", "https://arcaplanet.vtexassets.com/arquivos/ids/251113-200-200/expecial-gatto-anatra-e-tacchino.jpg?v=1781699979"),
  new Food("Masticativo", "gatto", "Un gioco alimentare perfetto per il tuo gatto, masticando questo prodotto rinforzerà e laverà i suoi denti!", "2,99", "https://arcaplanet.vtexassets.com/arquivos/ids/226897-200-200/virtus-mini-strips-gatto-salmone.jpg?v=1781655342"),
  new Food("Premio", "gatto", "Il prodotto adatto per premiare il tuo gatto per comportamenti corretti o per la giusta esecuzione dei suoi esercizi!", "9,59", "https://arcaplanet.vtexassets.com/arquivos/ids/288454-200-200/catisfaction-snack-gatto-formaggio-180g.jpg?v=1781678785"),
  //Cane
  new Toy("Piscinetta", "cane", "La piscina per cani di Pet Pool in robusta plastica è ideale per rinfrescare il tuo amico a quattro zampe nelle giornate calde.", "27,99", "https://arcaplanet.vtexassets.com/arquivos/ids/270541-200-200/pet-around-you-piscina-per-cani.jpg?v=1781647599"),
  new Toy("Gioco masticativo", "cane", "CONG Classic, da oltre 30 anni fa divertire il tuo cane. I giochi Cong rispondono ai bisogni di diversi tipi di cane (taglia, razza, età), stimolano la curiosità e sono robusti e durevoli grazie ai materiali d'alta qualità.", "8,99", "https://arcaplanet.vtexassets.com/arquivos/ids/256590-200-200/kong-classic1.jpg?v=1781655282"),
  new Toy("Palla", "cane", "CONG SqueakAir Balls è perfetto per i giochi di lancio del tuo cane. Questo divertimento combina la classica pallina da tennis ma con l'aggiunta dello squeak per regalare al tuo Fido un divertimento per ore.", "6,99", "https://arcaplanet.vtexassets.com/arquivos/ids/256054-200-200/Squeakair-001.jpg?v=1781647612"),
  new Toy("Peluche", "cane", "La giraffa Wiggi CONG è un gioco per cane realizzato con materiali di qualità. Creato con corpo pieno in robusto lattice è il gioco ideale per il divertimento del tuo amico a quattro zampe. ", "8,40", "https://arcaplanet.vtexassets.com/arquivos/ids/223644-200-200/kong-cane-wiggi-giraffe.jpg?v=1781396079"),
  //Gatto
  new Toy("Tiragraffi", "gatto", "Grazie al Tiragraffi Tidvia Rosa Antico i vostri gatti possono graffiare, appollaiarsi, nascondersi, arrampicarsi e rilassarsi come meglio credono.", "22.99", "https://arcaplanet.vtexassets.com/arquivos/ids/265339-200-200/trixie-tiragraffi-livia-rosa-antico-64cm.jpg?v=1781673132"),
  new Toy("Topolino", "gatto", "Yep! Gatto Topolino Righe 5X11CM", "0,99", "https://arcaplanet.vtexassets.com/arquivos/ids/209781-200-200/YES--topolino-a-righe-gioco-gatto.jpg?v=1781568933"),
  new Toy("Palle erbagatta", "gatto", "Gioco Gatto Euforia Palla risveglia l’istinto felino e dona benessere al gatto. Aiuta il felino nella cura dei denti ed è Cat-Friendly senza sostanze artificiali e tossiche.", "2,99", "https://arcaplanet.vtexassets.com/arquivos/ids/271976-200-200/GIOCO-GATTO-EUPHORIA-PALLA-CATNIP.jpg?v=1781655528"),
  new Toy("Palla peluche", "gatto", "Gioco per gatti Cthulhu Pirate, con catnip in dotazione per attirare l'attenzione dell'animale e invogliarlo a giocare.", "1,99", "https://arcaplanet.vtexassets.com/arquivos/ids/227172-200-200/yes-pallina-peluche-rosa-con-coda-cm-4-5x12.jpg?v=1781688565"),
  //Cane
  new Doghouse("Cuccia esterna", "cane", "La cuccia per cani Eco Loggia è la cuccia ideale proteggere il tuo amico a quattro zampe dalle fredde serate invernali.", "69,99", "https://arcaplanet.vtexassets.com/arquivos/ids/225622-200-200/p-a-y--canile-eco-lodge-medium.jpg?v=1781706463"),
  new Doghouse("Cuccia rettangolare", "cane", "Cuccia Rettangolare righe. La cuccetta MoonMat è prodotta da artigiani italiani utilizzando materiali di ottima qualità.", "27,99", "https://arcaplanet.vtexassets.com/arquivos/ids/273263-200-200/LUNA-TEO-CUCCIA-RETT.-CM.-60-RIGHE.jpg?v=1780877974"),
  new Doghouse("Brandina in Alluminio", "cane", "Brandina in Alluminio color Vinaccia per cani di Must è realizzata in modo tale da renderla leggera e resistente.", "29,99", "https://arcaplanet.vtexassets.com/arquivos/ids/280147-200-200/brandina-per-cane.jpg?v=1781568987"),
  new Doghouse("Cuscino Nautics", "cane", "Il cuscino per cani e gatti Natics di Crux, creato per donare al tuo peloso uno spazio dove riposarsi nel migliore dei modi.", "18,99", "https://arcaplanet.vtexassets.com/arquivos/ids/264194-200-200/croci-cuscino-nautica.jpg?v=1781692985"),
  //Gatto
  new Doghouse("Cesta Relax grigia", "gatto", "Cesta Relax è una cuccia per cani e gatti pratica e versatile. Fabbricata interamente in plastica, solida e robusta, mostra una piacevole forma arrotondata per accogliere i vostri animali.", "13,99", "https://arcaplanet.vtexassets.com/arquivos/ids/226704-200-200/ferplast-cane-siesta-deluxe-grigio.jpg?v=1781655251"),
  new Doghouse("Cat View Lettino da Finestra", "gatto", "Regala al tuo micio un momento di puro relax per osservare il mondo dall'alto con il lettino da finestra Pets Federation!", "28,90", "https://arcaplanet.vtexassets.com/arquivos/ids/224447-200-200/cat-view-gatto-lettino-da-finestra-grigio.jpg?v=1781053840"),
  new Doghouse("Cuccia per Calorifero", "gatto", "La cuccia da calorifero per gatti Janet di Yep!, è una morbida cuccia in peluche da appendere al calorifero.", "15,99", "https://arcaplanet.vtexassets.com/arquivos/ids/209724-200-200/YES--Cuccia-per-gatti-da-calorifero-Jane.jpg?v=1781223458"),
  new Doghouse("Cuccia Igloo Types", "gatto", "Types è una cuccia per gatti e per cani di piccole dimensioni, realizzata in feltro. Il prodotto a forma di igloo di Trixy è ideale per far riposare e dormire in tutta tranquillità il tuo pet.", "61,99", "https://arcaplanet.vtexassets.com/arquivos/ids/265863-200-200/trixie-cuccia-igloo-tipi-per-gatto-e-cane.jpg?v=1780207300"),
];